# Generated by Django 3.2.13 on 2022-06-09 15:20

from django.db import migrations, models
import project_sitesetting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=120, verbose_name='توضیحات')),
                ('place', models.CharField(max_length=120, verbose_name='آدرس')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('phone', models.IntegerField(verbose_name='شماره تماس')),
                ('slider', models.ImageField(blank=True, null=True, upload_to=project_sitesetting.models.upload_image_path)),
            ],
            options={
                'verbose_name': 'ادرس و تلفن',
                'verbose_name_plural': 'ادرس و تلفن',
            },
        ),
    ]
