# Generated by Django 3.2.13 on 2022-06-07 10:30

from django.db import migrations, models
import project_slider_andishkadeh.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderAndishkadeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=120, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=project_slider_andishkadeh.models.upload_image_path)),
            ],
            options={
                'verbose_name': 'اسلایدر اندیشکده',
                'verbose_name_plural': 'اسلایدر اندیشکده',
            },
        ),
    ]
