# Generated by Django 3.2.13 on 2022-06-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_slider_andishkadeh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderandishkadeh',
            options={'verbose_name': 'اسلایدر گروه های علمی و پژوهشی', 'verbose_name_plural': 'اسلایدر گروه های علمی و پژوهشی'},
        ),
    ]
