# Generated by Django 3.2.13 on 2022-06-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_product', '0002_product_slider_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slider_image',
            new_name='image',
        ),
    ]
