# Generated by Django 3.2.13 on 2022-06-02 12:45

from django.db import migrations, models
import project_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_product', '0003_rename_slider_image_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=project_product.models.upload_image_path)),
            ],
            options={
                'verbose_name': ('اسلایدر',),
                'verbose_name_plural': 'اسلایدر',
            },
        ),
    ]
