# Generated by Django 3.2.13 on 2022-06-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_product', '0004_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
