# Generated by Django 3.2.13 on 2022-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_product', '0005_delete_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=True, max_length=120, unique=True),
        ),
    ]
