# Generated by Django 3.2.13 on 2022-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_product', '0006_auto_20220607_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
