# Generated by Django 3.2.13 on 2022-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_product', '0009_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
