# Generated by Django 3.2.13 on 2022-06-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_product', '0011_remove_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ('اندیشکده ها',), 'verbose_name_plural': 'اندیشکده ها'},
        ),
    ]
