# Generated by Django 3.2.13 on 2022-06-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_product', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': (' گروه های علمی و پژوهشی',), 'verbose_name_plural': ' گروه های علمی و پژوهشی'},
        ),
    ]
