# Generated by Django 3.2.13 on 2022-06-07 16:54

from django.db import migrations, models
import project_aboutus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=120, verbose_name='عنوان')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('slider', models.ImageField(blank=True, null=True, upload_to=project_aboutus.models.upload_image_path)),
            ],
            options={
                'verbose_name': 'درباره ی ما',
            },
        ),
    ]
