# Generated by Django 3.2.13 on 2022-06-07 18:05

from django.db import migrations, models
import project_aboutus.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ی ما', 'verbose_name_plural': 'درباره ی ما'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=project_aboutus.models.upload_image_path),
        ),
    ]
