# Generated by Django 3.2.13 on 2022-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_aboutus', '0002_auto_20220607_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='توضیحات'),
        ),
    ]
