# Generated by Django 3.2.13 on 2022-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_aboutus', '0003_alter_aboutus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='توضیحات'),
        ),
    ]
