# Generated by Django 3.2.13 on 2022-06-10 11:08

from django.db import migrations, models
import project_slider_research.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(blank=True, null=True, upload_to=project_slider_research.models.upload_image_path)),
            ],
            options={
                'verbose_name': 'اسلایدر پژوهش های مرکز',
                'verbose_name_plural': 'اسلایدر پژوهش های مرکز',
            },
        ),
    ]
