# Generated by Django 3.2.13 on 2022-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_slider_research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderresearch',
            name='title',
            field=models.CharField(default='title', max_length=120, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
