# Generated by Django 3.2.13 on 2022-06-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
    ]
