# Generated by Django 3.2.13 on 2022-06-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_slider', '0003_auto_20220601_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': ('اسلایدر',), 'verbose_name_plural': 'اسلایدر'},
        ),
    ]
