# Generated by Django 3.2.13 on 2022-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
