# Generated by Django 3.2.13 on 2022-06-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_contactus', '0002_alter_contactus_fullname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
    ]
