# Generated by Django 3.2.13 on 2022-06-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_contactus', '0003_alter_contactus_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
