# Generated by Django 3.2.13 on 2022-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_contactus', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(verbose_name='شماره'),
        ),
    ]
