# Generated by Django 3.2.13 on 2022-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'مقالات و نشست ها', 'verbose_name_plural': 'مقالات و نشست ها'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='slider',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=4000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=120, verbose_name='عنوان مقاله یا نشست'),
        ),
    ]
