# Generated by Django 3.2.13 on 2022-06-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0002_auto_20220610_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='purpose',
            field=models.TextField(default='default', max_length=200, verbose_name='اهداف نشست یا مقاله'),
            preserve_default=False,
        ),
    ]
