# Generated by Django 3.2.13 on 2022-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0003_blog_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description2',
            field=models.TextField(default='default', max_length=400, verbose_name='ادامه توضیحات'),
            preserve_default=False,
        ),
    ]
