# Generated by Django 3.2.13 on 2022-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0004_blog_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description2',
            field=models.TextField(max_length=4000, verbose_name='ادامه توضیحات'),
        ),
    ]
