# Generated by Django 3.2.13 on 2022-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0006_auto_20220614_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='1', max_length=200),
        ),
    ]
