# Generated by Django 3.2.13 on 2022-06-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
