# Generated by Django 3.2.13 on 2022-06-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0011_auto_20220614_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='default', max_length=200),
        ),
    ]
