# Generated by Django 3.2.13 on 2022-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0012_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
    ]
