# Generated by Django 3.2.13 on 2022-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0014_auto_20220614_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'دیدگاه ها', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='name', max_length=10, verbose_name='نام شما'),
        ),
    ]
