# Generated by Django 3.2.13 on 2022-06-11 10:39

from django.db import migrations, models
import project_slider_blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان اسلایدر')),
                ('slider', models.ImageField(blank=True, null=True, upload_to=project_slider_blog.models.upload_image_path)),
            ],
            options={
                'verbose_name': ('اسلایدر مقالات و نشست ها',),
                'verbose_name_plural': 'اسلایدر مقالات و نشست ها',
            },
        ),
    ]
